// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQpQE3FNpNZxjb38aqOFZfl74b24gnCtQ',
    appId: '1:1043528514190:web:49a33cf293e9198191e7df',
    messagingSenderId: '1043528514190',
    projectId: 'mysubscriptionsfbase',
    authDomain: 'mysubscriptionsfbase.firebaseapp.com',
    storageBucket: 'mysubscriptionsfbase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjo9HglIQRGUqGPAik_jLRwvBMNzMTFtw',
    appId: '1:1043528514190:android:15cf5ce068d9515b91e7df',
    messagingSenderId: '1043528514190',
    projectId: 'mysubscriptionsfbase',
    storageBucket: 'mysubscriptionsfbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq5YWLxfO4BxPCAn7o_m7E_2ded6EbZUg',
    appId: '1:1043528514190:ios:6a247f6fb6a80a1791e7df',
    messagingSenderId: '1043528514190',
    projectId: 'mysubscriptionsfbase',
    storageBucket: 'mysubscriptionsfbase.firebasestorage.app',
    iosBundleId: 'com.devlab.mySubscriptions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq5YWLxfO4BxPCAn7o_m7E_2ded6EbZUg',
    appId: '1:1043528514190:ios:6a247f6fb6a80a1791e7df',
    messagingSenderId: '1043528514190',
    projectId: 'mysubscriptionsfbase',
    storageBucket: 'mysubscriptionsfbase.firebasestorage.app',
    iosBundleId: 'com.devlab.mySubscriptions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQpQE3FNpNZxjb38aqOFZfl74b24gnCtQ',
    appId: '1:1043528514190:web:3c939b5c227f76ff91e7df',
    messagingSenderId: '1043528514190',
    projectId: 'mysubscriptionsfbase',
    authDomain: 'mysubscriptionsfbase.firebaseapp.com',
    storageBucket: 'mysubscriptionsfbase.firebasestorage.app',
  );
}
