import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);
  final Locale locale;
  bool get isArabic => locale.languageCode == 'ar';

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const LocalizationsDelegate<AppLocalizations> delegate = _Delegate();

  String text(String key) =>
      (_values[locale.languageCode] ?? _values['en']!)[key] ?? key;

  static const _values = <String, Map<String, String>>{
    'ar': {
      'appName': 'SubTrack',
      'hello': 'مرحباً بك',
      'home': 'الرئيسية',
      'stats': 'الإحصاءات',
      'settings': 'الإعدادات',
      'add': 'إضافة اشتراك',
      'edit': 'تعديل الاشتراك',
      'monthlySpend': 'المصاريف الشهرية',
      'yearlySpend': 'المصاريف السنوية',
      'active': 'اشتراك نشط',
      'upcoming': 'التجديدات القادمة',
      'within7': 'خلال 7 أيام',
      'allSubscriptions': 'كل الاشتراكات',
      'noSubscriptions': 'لا توجد اشتراكات بعد',
      'emptyHint': 'أضف خدماتك لتعرف مصروفك وموعد التجديد القادم.',
      'quickAdd': 'إضافة سريعة',
      'days': 'أيام',
      'today': 'اليوم',
      'tomorrow': 'غداً',
      'renewal': 'التجديد',
      'delete': 'حذف',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'confirmDelete': 'هل تريد حذف هذا الاشتراك؟',
      'disableHint': 'اضغط مطولاً للتفعيل أو التعطيل',
      'name': 'اسم الاشتراك',
      'category': 'الفئة',
      'price': 'السعر',
      'currency': 'العملة',
      'billingCycle': 'دورة الفوترة',
      'monthly': 'شهري',
      'yearly': 'سنوي',
      'weekly': 'أسبوعي',
      'startDate': 'تاريخ البداية',
      'nextRenewal': 'التجديد القادم',
      'notes': 'ملاحظات (اختياري)',
      'cardColor': 'لون البطاقة',
      'reminder': 'ذكّرني قبل التجديد',
      'reminderDays': 'موعد التذكير',
      'oneDay': 'قبل يوم',
      'threeDays': 'قبل 3 أيام',
      'sevenDays': 'قبل 7 أيام',
      'required': 'هذا الحقل مطلوب',
      'invalidPrice': 'أدخل سعراً صحيحاً',
      'saved': 'تم حفظ الاشتراك',
      'deleted': 'تم حذف الاشتراك',
      'disabled': 'تم تعطيل الاشتراك',
      'enabled': 'تم تفعيل الاشتراك',
      'thisMonth': 'هذا الشهر',
      'thisYear': 'هذا العام',
      'allTime': 'كل الوقت',
      'last6Months': 'المصاريف الشهرية',
      'byCategory': 'حسب الفئة',
      'expensive': 'أغلى اشتراكاتك',
      'savingTip': 'إذا ألغيت الأغلى ستوفّر سنوياً',
      'noStats': 'أضف اشتراكاً لعرض الإحصاءات',
      'appearance': 'المظهر',
      'light': 'فاتح',
      'dark': 'داكن',
      'system': 'تلقائي',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'baseCurrency': 'عملة العرض الأساسية',
      'data': 'البيانات',
      'export': 'تصدير نسخة JSON',
      'import': 'استيراد نسخة JSON',
      'clearAll': 'حذف كل البيانات',
      'clearTitle': 'حذف كل البيانات؟',
      'clearWarning': 'سيتم حذف كل الاشتراكات نهائياً. اضغط تأكيد للمتابعة.',
      'confirm': 'تأكيد',
      'exported': 'تم تجهيز النسخة الاحتياطية',
      'imported': 'تم استيراد البيانات',
      'error': 'حدث خطأ، حاول مجدداً',
      'about': 'عن التطبيق',
      'version': 'الإصدار 1.0.0',
      'offline': 'يعمل بالكامل دون إنترنت',
      'comparison': 'مقارنة بالشهر السابق',
      'stable': 'إنفاقك مستقر',
      'notificationTime': 'وقت التذكير اليومي',
      'chooseTime': 'اختيار الوقت',
      'suggestions': 'اختر اشتراكاً',
      'otherSubscription': 'اشتراك آخر',
      'categories': 'الفئات',
      'addCategory': 'إضافة فئة',
      'categoryName': 'اسم الفئة',
      'chooseIcon': 'اختر أيقونة',
      'chooseLogo': 'اختيار شعار من الهاتف',
      'logoSelected': 'تم اختيار الشعار',
      'items': 'اشتراكات',
      'addItem': 'إضافة اشتراك داخل الفئة',
      'deleteCategory': 'حذف الفئة؟',
      'deleteCategoryConfirm': 'ستُنقل اشتراكات هذه الفئة إلى فئة أخرى.',
    },
    'en': {
      'appName': 'SubTrack',
      'hello': 'Welcome back',
      'home': 'Home',
      'stats': 'Insights',
      'settings': 'Settings',
      'add': 'Add subscription',
      'edit': 'Edit subscription',
      'monthlySpend': 'Monthly spend',
      'yearlySpend': 'Yearly spend',
      'active': 'active',
      'upcoming': 'Upcoming renewals',
      'within7': 'Within 7 days',
      'allSubscriptions': 'All subscriptions',
      'noSubscriptions': 'No subscriptions yet',
      'emptyHint': 'Add your services to track spending and renewals.',
      'quickAdd': 'Quick add',
      'days': 'days',
      'today': 'Today',
      'tomorrow': 'Tomorrow',
      'renewal': 'Renews',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'save': 'Save',
      'confirmDelete': 'Delete this subscription?',
      'disableHint': 'Long press to enable or pause',
      'name': 'Subscription name',
      'category': 'Category',
      'price': 'Price',
      'currency': 'Currency',
      'billingCycle': 'Billing cycle',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'weekly': 'Weekly',
      'startDate': 'Start date',
      'nextRenewal': 'Next renewal',
      'notes': 'Notes (optional)',
      'cardColor': 'Card color',
      'reminder': 'Remind me before renewal',
      'reminderDays': 'Reminder date',
      'oneDay': '1 day before',
      'threeDays': '3 days before',
      'sevenDays': '7 days before',
      'required': 'This field is required',
      'invalidPrice': 'Enter a valid price',
      'saved': 'Subscription saved',
      'deleted': 'Subscription deleted',
      'disabled': 'Subscription paused',
      'enabled': 'Subscription enabled',
      'thisMonth': 'This month',
      'thisYear': 'This year',
      'allTime': 'All time',
      'last6Months': 'Monthly expenses',
      'byCategory': 'By category',
      'expensive': 'Most expensive',
      'savingTip': 'Cancel the most expensive to save yearly',
      'noStats': 'Add a subscription to see insights',
      'appearance': 'Appearance',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'language': 'Language',
      'arabic': 'العربية',
      'english': 'English',
      'baseCurrency': 'Display currency',
      'data': 'Data',
      'export': 'Export JSON backup',
      'import': 'Import JSON backup',
      'clearAll': 'Delete all data',
      'clearTitle': 'Delete all data?',
      'clearWarning':
          'All subscriptions will be permanently deleted. Tap confirm to continue.',
      'confirm': 'Confirm',
      'exported': 'Backup is ready',
      'imported': 'Data imported',
      'error': 'Something went wrong. Try again.',
      'about': 'About',
      'version': 'Version 1.0.0',
      'offline': 'Works entirely offline',
      'comparison': 'Compared with last month',
      'stable': 'Your spending is stable',
      'notificationTime': 'Daily reminder time',
      'chooseTime': 'Choose time',
      'suggestions': 'Choose a subscription',
      'otherSubscription': 'Other subscription',
      'categories': 'Categories',
      'addCategory': 'Add category',
      'categoryName': 'Category name',
      'chooseIcon': 'Choose an icon',
      'chooseLogo': 'Choose logo from phone',
      'logoSelected': 'Logo selected',
      'items': 'items',
      'addItem': 'Add subscription to category',
      'deleteCategory': 'Delete category?',
      'deleteCategoryConfirm':
          'Subscriptions in this category will move to Others.',
    },
  };
}

class _Delegate extends LocalizationsDelegate<AppLocalizations> {
  const _Delegate();
  @override
  bool isSupported(Locale locale) => ['ar', 'en'].contains(locale.languageCode);
  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));
  @override
  bool shouldReload(_Delegate old) => false;
}

extension AppStringsContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
